"""
Everything that turns a meeting's notes into a downloadable file lives here:
PDF, Word, and an .ics calendar for the action items. Each function writes to
the exports/ folder and returns the path, which the routes then send back.
"""

import os
from datetime import datetime, timedelta
from fpdf import FPDF
from docx import Document
from docx.shared import Pt, RGBColor

def _get_export_dir():
    local_path = os.path.join(os.path.dirname(__file__), "exports")
    try:
        os.makedirs(local_path, exist_ok=True)
        test_file = os.path.join(local_path, ".write_test")
        with open(test_file, "w") as f:
            f.write("ok")
        os.remove(test_file)
        return local_path
    except (OSError, PermissionError):
        tmp_path = os.path.join("/tmp", "exports")
        os.makedirs(tmp_path, exist_ok=True)
        return tmp_path


EXPORT_DIR = _get_export_dir()


def _clean(text):
    # fpdf2's core fonts are Latin-1 only, so swap the smart quotes / dashes
    # and drop anything else it can't render instead of letting it throw.
    return (str(text)
            .replace("’", "'").replace("‘", "'")
            .replace("“", '"').replace("”", '"')
            .replace("—", "-").replace("–", "-")
            .encode("latin-1", "replace").decode("latin-1"))


def make_pdf(title, notes):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # I ran into fpdf's "not enough horizontal space" error when mixing cell()
    # and multi_cell(), so everything goes through these two helpers which reset
    # x to the left margin first and always use multi_cell.
    def write_block(text, size=11, style="", color=(30, 30, 30), gap=4):
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", style, size)
        pdf.set_text_color(*color)
        pdf.multi_cell(0, 6, _clean(text))
        pdf.ln(gap)

    def heading(text):
        write_block(text, size=13, style="B", color=(30, 60, 120), gap=1)

    def bullets(lines):
        for line in lines:
            write_block("- " + str(line), size=11, gap=1)
        pdf.ln(3)

    write_block(title, size=18, style="B", color=(30, 60, 120), gap=1)
    write_block("Generated by TalkToText Pro - " +
                datetime.now().strftime("%d %b %Y %H:%M"),
                size=10, color=(120, 120, 120), gap=6)

    if notes.get("tldr"):
        write_block("In a nutshell: " + notes.get("tldr", ""),
                    size=11, style="B", color=(60, 80, 160))

    heading("Summary")
    write_block(notes.get("summary", ""))

    heading("Key Discussion Points")
    bullets(notes.get("key_points", []))
    heading("Decisions Made")
    bullets(notes.get("decisions", []))

    heading("Action Items")
    bullets([
        f"{a.get('task','')}  (Owner: {a.get('owner','Unassigned')}, "
        f"Due: {a.get('deadline','Not specified')}, "
        f"Priority: {a.get('priority','Medium')})"
        for a in notes.get("action_items", [])
    ])

    sentiment = notes.get("sentiment", {})
    heading("Sentiment")
    write_block(f"{sentiment.get('label','Neutral')} - "
                f"{sentiment.get('explanation','')}")

    safe = "".join(c for c in title if c.isalnum() or c in " -_")[:40].strip()
    path = os.path.join(EXPORT_DIR, f"{safe or 'meeting'}.pdf")
    pdf.output(path)
    return path


def make_docx(title, notes):
    doc = Document()

    doc.add_heading(title, level=0)
    subtitle = doc.add_paragraph(
        "Generated by TalkToText Pro - " +
        datetime.now().strftime("%d %b %Y %H:%M")
    )
    subtitle.runs[0].italic = True

    if notes.get("tldr"):
        tldr_p = doc.add_paragraph()
        tldr_p.add_run("In a nutshell: " + notes.get("tldr", "")).bold = True

    doc.add_heading("Summary", level=1)
    doc.add_paragraph(notes.get("summary", ""))

    doc.add_heading("Key Discussion Points", level=1)
    for point in notes.get("key_points", []):
        doc.add_paragraph(point, style="List Bullet")

    doc.add_heading("Decisions Made", level=1)
    for decision in notes.get("decisions", []):
        doc.add_paragraph(decision, style="List Bullet")

    # Action items read nicer as a table than a bullet list.
    doc.add_heading("Action Items", level=1)
    items = notes.get("action_items", [])
    if items:
        table = doc.add_table(rows=1, cols=4)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text, hdr[1].text = "Task", "Owner"
        hdr[2].text, hdr[3].text = "Deadline", "Priority"
        for a in items:
            row = table.add_row().cells
            row[0].text = str(a.get("task", ""))
            row[1].text = str(a.get("owner", "Unassigned"))
            row[2].text = str(a.get("deadline", "Not specified"))
            row[3].text = str(a.get("priority", "Medium"))
    else:
        doc.add_paragraph("No action items found.")

    doc.add_heading("Sentiment", level=1)
    sentiment = notes.get("sentiment", {})
    doc.add_paragraph(f"{sentiment.get('label','Neutral')} — "
                      f"{sentiment.get('explanation','')}")

    safe = "".join(c for c in title if c.isalnum() or c in " -_")[:40].strip()
    path = os.path.join(EXPORT_DIR, f"{safe or 'meeting'}.docx")
    doc.save(path)
    return path


def make_ics(title, action_items):
    # Each action item becomes an all-day event on its deadline (or tomorrow if
    # there isn't one). Opens in Google Calendar, Outlook, Apple Calendar, etc.
    def esc(t):
        return str(t).replace(",", "\\,").replace(";", "\\;").replace("\n", " ")

    lines = ["BEGIN:VCALENDAR", "VERSION:2.0",
             "PRODID:-//TalkToText Pro//EN", "CALSCALE:GREGORIAN"]

    tomorrow = datetime.now() + timedelta(days=1)
    for i, a in enumerate(action_items):
        day = tomorrow
        raw = str(a.get("deadline", "")).strip()
        for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y", "%B %d, %Y", "%d %B %Y"):
            try:
                day = datetime.strptime(raw, fmt)
                break
            except ValueError:
                continue
        stamp = day.strftime("%Y%m%d")
        summary = esc(a.get("task", "Action item"))
        owner = esc(a.get("owner", "Unassigned"))
        priority = esc(a.get("priority", "Medium"))

        lines += [
            "BEGIN:VEVENT",
            f"UID:ttp-{i}-{stamp}@talktotext",
            f"DTSTART;VALUE=DATE:{stamp}",
            f"SUMMARY:{summary}",
            f"DESCRIPTION:From meeting '{esc(title)}'. Owner: {owner}. "
            f"Priority: {priority}.",
            "END:VEVENT",
        ]

    lines.append("END:VCALENDAR")

    safe = "".join(c for c in title if c.isalnum() or c in " -_")[:40].strip()
    path = os.path.join(EXPORT_DIR, f"{safe or 'meeting'}_tasks.ics")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\r\n".join(lines))
    return path
